country_list = ['DENMARK',
                'MALAYSIA',
                'EGYPT',
                'LUXEMBOURG',
                'NEW ZEALAND',
                'OMAN',
                'IRAN',
                'ESTONIA',
                'RWANDA',
                'VANUATU',
                'FINLAND',
                'AUSTRALIA',
                'AZERBAIJAN',
                'SOUTH AFRICA',
                'IRELAND',
                'GERMANY',
                'BELGIUM',
                'CROATIA',
                'SWEDEN',
                'NICARAGUA'
                ]
