word_list = ['Denmark',
             'Malaysia',
             'Egypt',
             'Luxembourg',
             'New Zealand',
             'Oman',
             'Iran',
             'Estonia',
             'Rwanda',
             'Vanuatu',
             'Denmark',
             'Australia',
             'Azerbaijan',
             'South Africa',
             'Ireland',
             'Germany',
             'Belgium',
             'Croatia',
             'Sweden',
             'Nicaragua'
             ]
