fd_list = ['Mozzarella',
           'Baguette',
           'Apple',
           'Tea',
           'Physalis',
           'Ice Cream',
           'Pizza',
           'Banana',
           'Quorn',
           'Chicken',
           'Popcorn',
           'Rice',
           'Yoghurt',
           'Cabbage',
           'Lemon',
           'Strawberry',
           'Coffee',
           'Juice',
           'Vodka',
           'Gin',
           ]
