fd_list = ['MOZZARELLA',
           'BAGUETTE',
           'APPLE',
           'TEA',
           'PHYSALIS',
           'ICE CREAM',
           'PIZZA',
           'BANANA',
           'QUORN',
           'CHICKEN',
           'POPCORN',
           'RICE',
           'YOGHURT',
           'CABBAGE',
           'LEMON',
           'STRAWBERRY',
           'COFFEE',
           'JUICE',
           'VODKA',
           'GIN',
           ]
